In [1]:
import pandas as pd
import numpy as np

In [7]:
movie_df = pd.read_csv('/content/movies.csv')

In [14]:
rating_df = pd.read_csv('/content/ratings.csv')

In [15]:
movie_df.head(10)

,movieId,title,genres
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,2,Jumanji (1995),Adventure|Children|Fantasy
2,3,Grumpier Old Men (1995),Comedy|Romance
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance
4,5,Father of the Bride Part II (1995),Comedy
5,6,Heat (1995),Action|Crime|Thriller
6,7,Sabrina (1995),Comedy|Romance
7,8,Tom and Huck (1995),Adventure|Children
8,9,Sudden Death (1995),Action
9,10,GoldenEye (1995),Action|Adventure|Thriller

In [16]:
rating_df.head(10)

   userId  movieId  rating  timestamp
0       1        1     4.0  964982703
1       1        3     4.0  964981247
2       1        6     4.0  964982224
3       1       47     5.0  964983815
4       1       50     5.0  964982931
5       1       70     3.0  964982400
6       1      101     5.0  964980868
7       1      110     4.0  964982176
8       1      151     5.0  964984041
9       1      157     5.0  964984100

In [17]:
combine_movie_rating = pd.merge(rating_df, movie_df, on='movieId')
combine_movie_rating.head(10)

,userId,movieId,rating,timestamp,title,genres
0,1,1,4.0,964982703,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,1,3,4.0,964981247,Grumpier Old Men (1995),Comedy|Romance
2,1,6,4.0,964982224,Heat (1995),Action|Crime|Thriller
3,1,47,5.0,964983815,Seven (a.k.a. Se7en) (1995),Mystery|Thriller
4,1,50,5.0,964982931,"Usual Suspects, The (1995)",Crime|Mystery|Thriller
5,1,70,3.0,964982400,From Dusk Till Dawn (1996),Action|Comedy|Horror|Thriller
6,1,101,5.0,964980868,Bottle Rocket (1996),Adventure|Comedy|Crime|Romance
7,1,110,4.0,964982176,Braveheart (1995),Action|Drama|War
8,1,151,5.0,964984041,Rob Roy (1995),Action|Drama|Romance|War
9,1,157,5.0,964984100,Canadian Bacon (1995),Comedy|War

In [18]:
columns = ['timestamp', 'genres']
combine_movie_rating = combine_movie_rating.drop(columns, axis=1)
combine_movie_rating.head(10)

   userId  movieId  rating                        title
0       1        1     4.0             Toy Story (1995)
1       1        3     4.0      Grumpier Old Men (1995)
2       1        6     4.0                  Heat (1995)
3       1       47     5.0  Seven (a.k.a. Se7en) (1995)
4       1       50     5.0   Usual Suspects, The (1995)
5       1       70     3.0   From Dusk Till Dawn (1996)
6       1      101     5.0         Bottle Rocket (1996)
7       1      110     4.0            Braveheart (1995)
8       1      151     5.0               Rob Roy (1995)
9       1      157     5.0        Canadian Bacon (1995)

In [20]:
combine_movie_rating = combine_movie_rating.dropna(axis = 0, subset = ['title'])

movie_ratingCount = (combine_movie_rating.
     groupby(by = ['title'])['rating'].
     count().
     reset_index().
     rename(columns = {'rating': 'totalRatingCount'})
     [['title', 'totalRatingCount']]
    )
movie_ratingCount.head(10)

                                     title  totalRatingCount
0                               '71 (2014)                 1
1  'Hellboy': The Seeds of Creation (2004)                 1
2                   'Round Midnight (1986)                 2
3                      'Salem's Lot (2004)                 1
4                'Til There Was You (1997)                 2
5          'Tis the Season for Love (2015)                 1
6                       'burbs, The (1989)                17
7                     'night Mother (1986)                 1
8              (500) Days of Summer (2009)                42
9           *batteries not included (1987)                 7

In [21]:
rating_with_totalRatingCount = combine_movie_rating.merge(movie_ratingCount, left_on = 'title', right_on = 'title', how = 'left')
rating_with_totalRatingCount.head(10)

   userId  movieId  rating                        title  totalRatingCount
0       1        1     4.0             Toy Story (1995)               215
1       1        3     4.0      Grumpier Old Men (1995)                52
2       1        6     4.0                  Heat (1995)               102
3       1       47     5.0  Seven (a.k.a. Se7en) (1995)               203
4       1       50     5.0   Usual Suspects, The (1995)               204
5       1       70     3.0   From Dusk Till Dawn (1996)                55
6       1      101     5.0         Bottle Rocket (1996)                23
7       1      110     4.0            Braveheart (1995)               237
8       1      151     5.0               Rob Roy (1995)                44
9       1      157     5.0        Canadian Bacon (1995)                11

In [22]:
user_rating = rating_with_totalRatingCount.drop_duplicates(['userId','title'])
user_rating.head(10)

   userId  movieId  rating                        title  totalRatingCount
0       1        1     4.0             Toy Story (1995)               215
1       1        3     4.0      Grumpier Old Men (1995)                52
2       1        6     4.0                  Heat (1995)               102
3       1       47     5.0  Seven (a.k.a. Se7en) (1995)               203
4       1       50     5.0   Usual Suspects, The (1995)               204
5       1       70     3.0   From Dusk Till Dawn (1996)                55
6       1      101     5.0         Bottle Rocket (1996)                23
7       1      110     4.0            Braveheart (1995)               237
8       1      151     5.0               Rob Roy (1995)                44
9       1      157     5.0        Canadian Bacon (1995)                11

In [23]:
movie_user_rating_pivot = user_rating.pivot(index = 'userId', columns = 'title', values = 'rating').fillna(0)
movie_user_rating_pivot.head(10)

title,'71 (2014),'Hellboy': The Seeds of Creation (2004),'Round Midnight (1986),'Salem's Lot (2004),'Til There Was You (1997),'Tis the Season for Love (2015),"'burbs, The (1989)",'night Mother (1986),(500) Days of Summer (2009),*batteries not included (1987),...,Zulu (2013),[REC] (2007),[REC]² (2009),[REC]³ 3 Génesis (2012),anohana: The Flower We Saw That Day - The Movie (2013),eXistenZ (1999),xXx (2002),xXx: State of the Union (2005),¡Three Amigos! (1986),À nous la liberté (Freedom for Us) (1931)
userId,,,,,,,,,,,,,,,,,,,,,
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
8,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
9,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
10,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [24]:
X = movie_user_rating_pivot.values.T
X.shape

(9719, 610)

In [25]:
import sklearn
from sklearn.decomposition import TruncatedSVD

SVD = TruncatedSVD(n_components=12, random_state=17)
matrix = SVD.fit_transform(X)
matrix.shape

(9719, 12)

In [26]:
import warnings
warnings.filterwarnings("ignore",category =RuntimeWarning)
corr = np.corrcoef(matrix)
corr.shape

(9719, 9719)

In [27]:
movie_title = movie_user_rating_pivot.columns
movie_title_list = list(movie_title)
coffey_hands = movie_title_list.index("Guardians of the Galaxy (2014)")

In [28]:
corr_coffey_hands  = corr[coffey_hands]
list(movie_title[(corr_coffey_hands >= 0.9)])

['Amazing Spider-Man, The (2012)',
 'Ant-Man (2015)',
 'Avatar (2009)',
 'Avengers, The (2012)',
 'Avengers: Age of Ultron (2015)',
 'Big Hero 6 (2014)',
 'Brave (2012)',
 'Captain America: The First Avenger (2011)',
 'Captain America: The Winter Soldier (2014)',
 'Cloudy with a Chance of Meatballs (2009)',
 'Dark Knight Rises, The (2012)',
 'Deadpool (2016)',
 'Deadpool 2 (2018)',
 'Despicable Me (2010)',
 'District 9 (2009)',
 'Django Unchained (2012)',
 'Doctor Strange (2016)',
 'Edge of Tomorrow (2014)',
 "Ender's Game (2013)",
 'Grand Budapest Hotel, The (2014)',
 'Gravity (2013)',
 'Guardians of the Galaxy (2014)',
 'Guardians of the Galaxy 2 (2017)',
 'Harry Potter and the Deathly Hallows: Part 1 (2010)',
 'Harry Potter and the Deathly Hallows: Part 2 (2011)',
 'Hobbit: An Unexpected Journey, The (2012)',
 'Hobbit: The Desolation of Smaug, The (2013)',
 'How to Train Your Dragon (2010)',
 'Hugo (2011)',
 'Inside Out (2015)',
 'Interstellar (2014)',
 'Iron Man (2008)',
 'Iron Man 2 (2010)',
 'John Wick (2014)',
 'Jurassic World (2015)',
 'Kingsman: The Golden Circle (2017)',
 'Kingsman: The Secret Service (2015)',
 'Kung Fu Panda (2008)',
 'Life of Pi (2012)',
 'Logan (2017)',
 'Looper (2012)',
 'Mad Max: Fury Road (2015)',
 'Man of Steel (2013)',
 'Mission: Impossible - Rogue Nation (2015)',
 'Need for Speed (2014)',
 'Now You See Me (2013)',
 'Oblivion (2013)',
 'Pirates of the Caribbean: On Stranger Tides (2011)',
 'Quantum of Solace (2008)',
 'Rogue One: A Star Wars Story (2016)',
 'Scott Pilgrim vs. the World (2010)',
 'Sherlock Holmes (2009)',
 'Sherlock Holmes: A Game of Shadows (2011)',
 'Skyfall (2012)',
 "Sorcerer's Apprentice, The (2010)",
 'Star Trek (2009)',
 'Star Trek Into Darkness (2013)',
 'Star Wars: Episode VII - The Force Awakens (2015)',
 'The Expendables 3 (2014)',
 'The Hunger Games (2012)',
 'The Hunger Games: Catching Fire (2013)',
 'The Hunger Games: Mockingjay - Part 1 (2014)',
 'The Lego Movie (2014)',
 'The Martian (2015)',
 'Thor (2011)',
 'Thor: The Dark World (2013)',
 'Toy Story 3 (2010)',
 'Up (2009)',
 'White House Down (2013)',
 'Wreck-It Ralph (2012)',
 'X-Men: Days of Future Past (2014)',
 'X-Men: First Class (2011)',
 'Zombieland (2009)',
 'Zootopia (2016)']